default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 19731213
  host: localhost

development:
  <<: *default
  database: git-app_rails7_development

test:
  <<: *default
  database: git-app_rails7_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
